version: "3.7"

services:
  frontend:
    image: phmarquesdev/lets-help-rs-frontend:latest
    container_name: lets-help-rs-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_REPORT_DELETE=${VITE_REPORT_DELETE}
      - VITE_PIX_KEY=${VITE_PIX_KEY}
      - VITE_DONATE_QRCODE=${VITE_DONATE_QRCODE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`letshelprs.online`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - web
    volumes:
      - .:/app/frontend 

networks:
  web:
    external: true
